# Generated by Django 2.1.1 on 2019-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctgapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='website',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
